<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pricing/v1/pricing.proto

namespace Pricing\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>pricing.v1.QuoteRequest</code>
 */
class QuoteRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>double amount = 1;</code>
     */
    protected $amount = 0.0;
    /**
     * Generated from protobuf field <code>int32 term_months = 2;</code>
     */
    protected $term_months = 0;
    /**
     * optional
     *
     * Generated from protobuf field <code>int32 risk_score = 3;</code>
     */
    protected $risk_score = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type float $amount
     *     @type int $term_months
     *     @type int $risk_score
     *           optional
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Pricing\V1\Pricing::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>double amount = 1;</code>
     * @return float
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     * Generated from protobuf field <code>double amount = 1;</code>
     * @param float $var
     * @return $this
     */
    public function setAmount($var)
    {
        GPBUtil::checkDouble($var);
        $this->amount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 term_months = 2;</code>
     * @return int
     */
    public function getTermMonths()
    {
        return $this->term_months;
    }

    /**
     * Generated from protobuf field <code>int32 term_months = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setTermMonths($var)
    {
        GPBUtil::checkInt32($var);
        $this->term_months = $var;

        return $this;
    }

    /**
     * optional
     *
     * Generated from protobuf field <code>int32 risk_score = 3;</code>
     * @return int
     */
    public function getRiskScore()
    {
        return $this->risk_score;
    }

    /**
     * optional
     *
     * Generated from protobuf field <code>int32 risk_score = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setRiskScore($var)
    {
        GPBUtil::checkInt32($var);
        $this->risk_score = $var;

        return $this;
    }

}

