<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pricing/v1/pricing.proto

namespace Pricing\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>pricing.v1.QuoteResponse</code>
 */
class QuoteResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>double interest_rate = 1;</code>
     */
    protected $interest_rate = 0.0;
    /**
     * Generated from protobuf field <code>double apr = 2;</code>
     */
    protected $apr = 0.0;
    /**
     * Generated from protobuf field <code>double monthly_payment = 3;</code>
     */
    protected $monthly_payment = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type float $interest_rate
     *     @type float $apr
     *     @type float $monthly_payment
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Pricing\V1\Pricing::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>double interest_rate = 1;</code>
     * @return float
     */
    public function getInterestRate()
    {
        return $this->interest_rate;
    }

    /**
     * Generated from protobuf field <code>double interest_rate = 1;</code>
     * @param float $var
     * @return $this
     */
    public function setInterestRate($var)
    {
        GPBUtil::checkDouble($var);
        $this->interest_rate = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double apr = 2;</code>
     * @return float
     */
    public function getApr()
    {
        return $this->apr;
    }

    /**
     * Generated from protobuf field <code>double apr = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setApr($var)
    {
        GPBUtil::checkDouble($var);
        $this->apr = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double monthly_payment = 3;</code>
     * @return float
     */
    public function getMonthlyPayment()
    {
        return $this->monthly_payment;
    }

    /**
     * Generated from protobuf field <code>double monthly_payment = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setMonthlyPayment($var)
    {
        GPBUtil::checkDouble($var);
        $this->monthly_payment = $var;

        return $this;
    }

}

