<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pricing/v1/pricing.proto

namespace GPBMetadata\Pricing\V1;

class Pricing
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
â
pricing/v1/pricing.proto
pricing.v1"G
QuoteRequest
amount (
term_months (

risk_score ("L
QuoteResponse
interest_rate (
apr (
monthly_payment (2N
PricingService<
Quote.pricing.v1.QuoteRequest.pricing.v1.QuoteResponseBKZ#pricingapi/gen/pricing/v1;pricingv1Ê
Pricing\\V1âGPBMetadata\\Pricing\\V1bproto3'
        , true);

        static::$is_initialized = true;
    }
}

