<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pricing/v1/pricing.proto

namespace GPBMetadata\Pricing\V1;

class Pricing
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xEC\x02\x0A\x18pricing/v1/pricing.proto\x12\x0Apricing.v1\"G\x0A\x0CQuoteRequest\x12\x0E\x0A\x06amount\x18\x01 \x01(\x01\x12\x13\x0A\x0Bterm_months\x18\x02 \x01(\x05\x12\x12\x0A\x0Arisk_score\x18\x03 \x01(\x05\"L\x0A\x0DQuoteResponse\x12\x15\x0A\x0Dinterest_rate\x18\x01 \x01(\x01\x12\x0B\x0A\x03apr\x18\x02 \x01(\x01\x12\x17\x0A\x0Fmonthly_payment\x18\x03 \x01(\x012N\x0A\x0EPricingService\x12<\x0A\x05Quote\x12\x18.pricing.v1.QuoteRequest\x1A\x19.pricing.v1.QuoteResponseBUZ-services/pricing-api/gen/pricing/v1;pricingv1\xCA\x02\x0APricing\\V1\xE2\x02\x16GPBMetadata\\Pricing\\V1b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

