# Docker Compose Template Examples for Go gRPC Services
# Copy these sections to docker-compose.yml when you create the other services

  services:
    # Event Gateway Service (Port 50052)
    event-gateway:
      build: 
        context: ../..
        dockerfile: services/common/Dockerfile.go-grpc
        args:
          SERVICE_NAME: event-gateway
          SERVICE_PORT: 50052
          PROTO_FILE: events/v1/events.proto  # Create this proto file
      ports:
        - "50052:50052"
      depends_on:
        - kafka
  
    # Offers Worker Service (Port 50053)
    offers-worker:
      build: 
        context: ../..
        dockerfile: services/common/Dockerfile.go-grpc
        args:
          SERVICE_NAME: offers-worker
          SERVICE_PORT: 50053
          PROTO_FILE: offers/v1/offers.proto  # Create this proto file
      ports:
        - "50053:50053"
      depends_on:
        - kafka
        - db
  
    # Kafka (for event-driven architecture)
    kafka:
      image: confluentinc/cp-kafka:latest
      environment:
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      ports:
        - "9092:9092"
      depends_on:
        - zookeeper
  
    # Zookeeper (required for Kafka)
    zookeeper:
      image: confluentinc/cp-zookeeper:latest
      environment:
        ZOOKEEPER_CLIENT_PORT: 2181
        ZOOKEEPER_TICK_TIME: 2000
      ports:
        - "2181:2181"