name: Pull Request Checks

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: grpc, protobuf
        tools: composer:v2
        
    - name: Cache PHP dependencies
      uses: actions/cache@v4
      with:
        path: backend/vendor
        key: ${{ runner.os }}-php-${{ hashFiles('backend/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
        
    - name: Install PHP dependencies
      run: |
        cd backend
        composer install --no-dev --optimize-autoloader --prefer-dist
        
    - name: PHP Syntax Check
      run: |
        cd backend
        find src -name "*.php" -exec php -l {} \;
        
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
        
    - name: Go Syntax Check
      run: |
        cd services/pricing-api
        go fmt ./...
        go vet ./...
        
    - name: Go Tests
      run: |
        cd services/pricing-api
        go test -v ./...
        
  docker-build-test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        service: [pricing-api]
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Cache Docker layers
      uses: actions/cache@v4
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ matrix.service }}-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-${{ matrix.service }}-
          
    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: services/${{ matrix.service }}/Dockerfile
        tags: test-${{ matrix.service }}:latest
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
        load: true
        
    - name: Test Docker image
      run: |
        docker run --rm test-${{ matrix.service }}:latest --version || true
        
    - name: Move cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  documentation:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Check README
      run: |
        if [ ! -f README.md ]; then
          echo "README.md is missing!"
          exit 1
        fi
        
    - name: Check API Documentation
      run: |
        if [ ! -f docs/api.md ] && [ ! -f protos/pricing/v1/pricing.proto ]; then
          echo "API documentation is missing!"
          exit 1
        fi